name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  obj1:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: install node v16
      #   uses: actions/setup-node@v3.1.1
      #   with:
      #     node-version: 16

      # - name: lint and build
      #   run: |
      #     yarn install
      #     yarn lint
      #     yarn build

  obj2:
    name: ssh
    runs-on: ubuntu-latest
    needs: obj1
    steps:
      - name: ssh
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ubuntu
          pass: ${{ secrets.SSH_PSSWD }}
          port: '22'
          first_ssh: |
            echo "Begin deploy"
            cd ~/Repo/21Sp-AcademicSystem
            bash ./backend/update.sh